# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 'OCaml Programming: Correct + Efficient + Beautiful'
author: Michael R. Clarkson et al.
copyright: "2021"
logo: lambda-light.png
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/cs3110/textbook # Online location of your book
  path_to_book: src  # Optional path to your book, relative to the repository root
  branch: jupyter  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  # Disable binder launch for now.  The public binderhub runs Ubuntu 18 which
  # does not have OPAM 2, so we can't easily create an OCaml kernel for it.
  # The only current alternative seems to be creating our own custom Dockerfile.
  # Delete the line below to restore the binder launch button.
  binderhub_url: ""

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  comments:
    hypothesis: true

parse:
  myst_substitutions:
    # The video_embed substitution below is essentially a macro to avoid
    # repeating all of the YouTube embed code for each video in the book.
    # The %%VID%% part of the src attribute is replaced by the YouTube video
    # id at each place where a video is linked in the textbook source.
    video_embed: '<div class="container16x9"><iframe src="https://www.youtube.com/embed/%%VID%%" class="responsive-iframe" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>'
    # Macros for exercises. It's tricky to get these to work for both HTML
    # and PDF. If you make any changes, be sure to check both outputs. If you
    # change the star symbol, make sure to change it at the end of chapter 1,
    # too.
    ex: |
      ---
      **Exercise: %%_NAME%% [%%STARS%%]**
    ex1: '{{ ex | replace("%%STARS%%", "&starf;") | replace("%%_NAME%%", "%%NAME%%")}}'
    ex2: '{{ ex | replace("%%STARS%%", "&starf;&starf;") | replace("%%_NAME%%", "%%NAME%%")}}'
    ex3: '{{ ex | replace("%%STARS%%", "&starf;&starf;&starf;") | replace("%%_NAME%%", "%%NAME%%")}}'
    ex4: '{{ ex | replace("%%STARS%%", "&starf;&starf;&starf;&starf;") | replace("%%_NAME%%", "%%NAME%%")}}'
    solutions: |
      Solutions to exercises are available to students in Cornell's CS 3110.
      Instructors at other institutions are welcome to contact Michael Clarkson
      for access.
  # Extensions to enable in the myst parser. See
  # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution